### ISSUE TITLE
开题模板参考文献没有放在表格中

### ISSUE THREAD

**Issue by Alexior319** [yangjingla/nudtbeamer#1]
官方给出的模板中，参考文献是放在表格中的：
![guanfang](https://github.com/yangjingla/nudtbeamer/assets/66198619/f9242ac3-44cf-45db-b0ea-d0d2a1b3b9aa)

而用这个项目中overleaf中的项目编译出来的文件中，参考文献是单独列出来的：
![xianyou](https://github.com/yangjingla/nudtbeamer/assets/66198619/67b0ca49-b052-45a2-b3c1-357164ed3433)

想请问如何修改能达到学校模板中所示的效果？非常感谢

**Comment by yangjingla** [comment]
同学你好👋，开题报告的引用需要使用biber进行编译，而overleaf上目前似乎只支持biblatex编译且无法配置修改，你可以先本地安装texlive环境，从overleaf下载整个项目到本地进行编译试一下

**Comment by yangjingla** [comment]
> 同学你好👋，开题报告的引用需要使用biber进行编译，而overleaf上目前似乎只支持biblatex编译且无法配置修改，你可以先本地安装texlive环境，从overleaf下载整个项目到本地进行编译试一下

**Comment by yangjingo** [comment]
> 官方给出的模板中，参考文献是放在表格中的： ![guanfang](https://private-user-images.githubusercontent.com/66198619/288762535-f9242ac3-44cf-45db-b0ea-d0d2a1b3b9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDE4NjUsIm5iZiI6MTcxMDI0MTU2NSwicGF0aCI6Ii82NjE5ODYxOS8yODg3NjI1MzUtZjkyNDJhYzMtNDRjZi00NWRiLWIwZWEtZDBkMmExYjNiOWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OWNkYWU1MDE2NGYwMzhiODM0YmY3NzNjYzkyOWFkNjk1M2FmMjI3ODQyN2Q0YjJmYmNmMDExZmFmOTU4ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kyd7RR6MrrTni_KOeDqtkHwu7_B1d-hP7ZbTdL74mZk)
> 
> 而用这个项目中overleaf中的项目编译出来的文件中，参考文献是单独列出来的： ![xianyou](https://private-user-images.githubusercontent.com/66198619/288762698-67b0ca49-b052-45a2-b3c1-357164ed3433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDE4NjUsIm5iZiI6MTcxMDI0MTU2NSwicGF0aCI6Ii82NjE5ODYxOS8yODg3NjI2OTgtNjdiMGNhNDktYjA1Mi00NWEyLWIzYzEtMzU3MTY0ZWQzNDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNTY0MzZhYzg3MDNlNmE3ODUzODllNjRjMmM3NDYyNWM5MDE3YzQ2MTU2YTBjOWJkNjczZmUxZGYyYWY1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWO-lXCGb-Q-Zl5bW294Hi_Zkk6pB-yR7qVqzvYj0Eg)
> 
> 想请问如何修改能达到学校模板中所示的效果？非常感谢

同学你好👋，开题报告的引用需要使用biber进行编译，而overleaf上目前似乎只支持biblatex编译且无法配置修改，你可以先本地安装texlive环境，从overleaf下载整个项目到本地进行编译试一下
